DEBUG - 2025-10-22 16:27:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:27:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:27:43 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:27:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:27:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:28:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:28:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-22 16:28:20 --> ErrorException: Undefined variable $stockValue
[Method: GET, Route: dashboard]
in APPPATH\Views\dashboard\central_admin.php on line 58.
 1 APPPATH\Views\dashboard\central_admin.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $stockValue', 'C:\\xampp\\htdocs\\Chakanoks\\app\\Views\\dashboard\\central_admin.php', 58)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\Chakanoks\\app\\Views\\dashboard\\central_admin.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('dashboard/central_admin', [], true)
 5 APPPATH\Controllers\Dashboard.php(13): view('dashboard/central_admin')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 16:28:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:28:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:28:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:28:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:28:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 16:38:05 --> mysqli_sql_exception: Duplicate entry 'Central Office Admin' for key 'username' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1841): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', NULL, false)
#4 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(2230): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\Chakanoks\app\Database\Seeds\UserSeeder.php(164): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\Chakanoks\system\Database\Seeder.php(149): App\Database\Seeds\UserSeeder->run()
#7 C:\xampp\htdocs\Chakanoks\app\Database\Seeds\DatabaseSeeder.php(15): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\Chakanoks\system\Database\Seeder.php(149): App\Database\Seeds\DatabaseSeeder->run()
#9 C:\xampp\htdocs\Chakanoks\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#10 C:\xampp\htdocs\Chakanoks\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#11 C:\xampp\htdocs\Chakanoks\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#12 C:\xampp\htdocs\Chakanoks\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#13 C:\xampp\htdocs\Chakanoks\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#14 C:\xampp\htdocs\Chakanoks\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#15 {main}
ERROR - 2025-10-22 16:47:32 --> mysqli_sql_exception: Duplicate entry 'FP001' for key 'product_code' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1841): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', NULL, false)
#4 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(2230): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\Chakanoks\app\Database\Seeds\ProductSeeder.php(210): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\Chakanoks\system\Database\Seeder.php(149): App\Database\Seeds\ProductSeeder->run()
#7 C:\xampp\htdocs\Chakanoks\app\Database\Seeds\DatabaseSeeder.php(16): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\Chakanoks\system\Database\Seeder.php(149): App\Database\Seeds\DatabaseSeeder->run()
#9 C:\xampp\htdocs\Chakanoks\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#10 C:\xampp\htdocs\Chakanoks\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#11 C:\xampp\htdocs\Chakanoks\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#12 C:\xampp\htdocs\Chakanoks\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#13 C:\xampp\htdocs\Chakanoks\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#14 C:\xampp\htdocs\Chakanoks\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#15 {main}
DEBUG - 2025-10-22 16:48:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:48:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:49:00 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:49:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 16:49:14 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-22 16:49:14 --> ErrorException: Undefined variable $stockValue
[Method: GET, Route: dashboard]
in APPPATH\Views\dashboard\central_admin.php on line 58.
 1 APPPATH\Views\dashboard\central_admin.php(58): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $stockValue', 'C:\\xampp\\htdocs\\Chakanoks\\app\\Views\\dashboard\\central_admin.php', 58)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\Chakanoks\\app\\Views\\dashboard\\central_admin.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('dashboard/central_admin', [], true)
 5 APPPATH\Controllers\Dashboard.php(13): view('dashboard/central_admin')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:08:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:08:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:08:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-22 17:08:41 --> TypeError: App\Controllers\Dashboard::index(): Return value must be of type string, CodeIgniter\HTTP\RedirectResponse returned
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 15.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:09:53 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:10:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:10:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-22 17:10:03 --> TypeError: App\Controllers\Dashboard::index(): Return value must be of type string, CodeIgniter\HTTP\RedirectResponse returned
[Method: GET, Route: dashboard]
in APPPATH\Controllers\Dashboard.php on line 15.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Dashboard->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:10:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:10:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:10:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:11:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:11:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:13:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:13:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-22 17:13:24 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: dashboard/branch-manager]
in APPPATH\Views\dashboard\branch_manager.php on line 95.
 1 APPPATH\Views\dashboard\branch_manager.php(95): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\xampp\\htdocs\\Chakanoks\\app\\Views\\dashboard\\branch_manager.php', 95)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\Chakanoks\\app\\Views\\dashboard\\branch_manager.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('dashboard/branch_manager', [], true)
 5 APPPATH\Controllers\BranchDashboard.php(66): view('dashboard/branch_manager', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\BranchDashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\BranchDashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:13:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:13:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:26:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:26:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:26:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:26:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2025-10-22 17:29:26 --> ParseError: syntax error, unexpected token "->", expecting "]"
[Method: GET, Route: dashboard/central]
in APPPATH\Controllers\CentralDashboard.php on line 81.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Chakanoks\\app\\Controllers\\CentralDashboard.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\CentralDashboard')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\CentralDashboard')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\CentralDashboard', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:29:34 --> ParseError: syntax error, unexpected token "->", expecting "]"
[Method: GET, Route: dashboard/central]
in APPPATH\Controllers\CentralDashboard.php on line 81.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\Chakanoks\\app\\Controllers\\CentralDashboard.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\CentralDashboard')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\CentralDashboard')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\CentralDashboard', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:38:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:38:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:38:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:38:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:38:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:38:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:38:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:38:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:39:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 17:39:06 --> mysqli_sql_exception: Unknown column 's.name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `s`.`nam...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`nam...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`nam...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`nam...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 17:39:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
[Method: GET, Route: dashboard/franchise]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 2 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:39:06 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 17:39:06\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 17:39:06\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 4 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:39:06 --> [Caused by] mysqli_sql_exception: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 17:39:06\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 17:39:06\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 17:39:06\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 5 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:39:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 17:39:10 --> mysqli_sql_exception: Unknown column 's.name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `po`.`po...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 17:39:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
[Method: GET, Route: dashboard/logistics]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 2 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:39:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 4 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:39:10 --> [Caused by] mysqli_sql_exception: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 5 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:39:17 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 17:39:31 --> mysqli_sql_exception: Unknown column 'name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `supplie...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplie...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplie...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplie...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\OrderController->create()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 17:39:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'name' in 'field list'
[Method: GET, Route: orders/create]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 2 APPPATH\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:39:31 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 4 APPPATH\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:39:31 --> [Caused by] mysqli_sql_exception: Unknown column 'name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 5 APPPATH\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:39:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:39:36 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:39:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:39:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:40:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:40:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:40:24 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:43:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:43:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:43:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:43:25 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:44:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:44:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:44:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:45:54 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:28 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:52 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:49:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:55:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:55:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:55:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:55:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:55:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:55:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 17:55:46 --> mysqli_sql_exception: Unknown column 'name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `supplie...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplie...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplie...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplie...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\OrderController->create()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 17:55:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'name' in 'field list'
[Method: GET, Route: orders/create]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 2 APPPATH\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:55:46 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 4 APPPATH\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 17:55:46 --> [Caused by] mysqli_sql_exception: Unknown column 'name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 5 APPPATH\Controllers\OrderController.php(24): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 17:55:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 17:55:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:00:08 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:00:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:00:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:00:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:00:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:00:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:00:45 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:04:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:04:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:04:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:04:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:50 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:05:59 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:06:01 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:06:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:06:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:06:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:06:47 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:06:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:07:12 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:07:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:07:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:07:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:07:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 18:07:59 --> mysqli_sql_exception: Duplicate entry 'FP001' for key 'product_code' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1841): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', NULL, false)
#4 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(2230): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\Chakanoks\app\Database\Seeds\ProductSeeder.php(210): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\Chakanoks\system\Database\Seeder.php(149): App\Database\Seeds\ProductSeeder->run()
#7 C:\xampp\htdocs\Chakanoks\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\Chakanoks\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\Chakanoks\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\Chakanoks\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Chakanoks\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Chakanoks\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-10-22 18:08:00 --> mysqli_sql_exception: Duplicate entry '1-3' for key 'product_id_branch_id' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `in...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `in...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `in...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1841): CodeIgniter\Database\BaseConnection->query('INSERT INTO `in...', NULL, false)
#4 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(2230): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\Chakanoks\app\Database\Seeds\InventorySeeder.php(59): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\Chakanoks\system\Database\Seeder.php(149): App\Database\Seeds\InventorySeeder->run()
#7 C:\xampp\htdocs\Chakanoks\system\Commands\Database\Seed.php(79): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\Chakanoks\system\CLI\Commands.php(74): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\Chakanoks\system\CLI\Console.php(47): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\Chakanoks\system\Boot.php(388): CodeIgniter\CLI\Console->run()
#11 C:\xampp\htdocs\Chakanoks\system\Boot.php(133): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\xampp\htdocs\Chakanoks\spark(87): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
DEBUG - 2025-10-22 18:08:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:08:57 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:08:58 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 18:08:58 --> mysqli_sql_exception: Unknown column 's.name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `po`.`po...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 18:08:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
[Method: GET, Route: dashboard/logistics]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 2 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:08:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 4 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:08:58 --> [Caused by] mysqli_sql_exception: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 5 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 18:09:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:09:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:09:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 18:09:05 --> mysqli_sql_exception: Unknown column 's.name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `po`.`po...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 18:09:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
[Method: GET, Route: dashboard/logistics]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 2 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:09:05 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 4 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:09:05 --> [Caused by] mysqli_sql_exception: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = \'ordered\'
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `po`.`po_number`, `b`.`branch_name`, `s`.`name` AS `supplier_name`, `po`.`expected_delivery_date`, `po`.`requested_date`
FROM `purchase_orders` `po`
LEFT JOIN `branches` `b` ON `b`.`branch_id` = `po`.`branch_id`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`status` = :po.status:
ORDER BY `po`.`expected_delivery_date` ASC
 LIMIT 10', [...], false)
 5 APPPATH\Controllers\LogisticsDashboard.php(24): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LogisticsDashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LogisticsDashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 18:09:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:09:26 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:09:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 18:09:27 --> mysqli_sql_exception: Unknown column 's.name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `s`.`nam...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`nam...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`nam...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`nam...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 18:09:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
[Method: GET, Route: dashboard/franchise]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 2 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:09:27 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:09:27\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:09:27\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 4 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:09:27 --> [Caused by] mysqli_sql_exception: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:09:27\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:09:27\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:09:27\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 5 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 18:09:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:09:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:09:46 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:09:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:10:04 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 18:10:04 --> mysqli_sql_exception: Unknown column 's.name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `s`.`nam...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`nam...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`nam...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`nam...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 18:10:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
[Method: GET, Route: dashboard/franchise]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 2 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:10:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:10:04\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:10:04\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 4 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:10:04 --> [Caused by] mysqli_sql_exception: Unknown column 's.name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:10:04\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:10:04\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= \'2025-09-22 18:10:04\'
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `s`.`name` as `supplier_name`, COUNT(*) as total_orders
FROM `purchase_orders` `po`
LEFT JOIN `suppliers` `s` ON `s`.`supplier_id` = `po`.`supplier_id`
WHERE `po`.`created_at` >= :po.created_at:
GROUP BY `s`.`name`
ORDER BY `total_orders` DESC
 LIMIT 10', [...], false)
 5 APPPATH\Controllers\FranchiseDashboard.php(33): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\FranchiseDashboard->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FranchiseDashboard))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 18:10:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-10-22 18:10:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-10-22 18:10:13 --> mysqli_sql_exception: Unknown column 'name' in 'field list' in C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\Chakanoks\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `supplie...', 0)
#1 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplie...')
#2 C:\xampp\htdocs\Chakanoks\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplie...')
#3 C:\xampp\htdocs\Chakanoks\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplie...', Array, false)
#4 C:\xampp\htdocs\Chakanoks\app\Controllers\OrderController.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(933): App\Controllers\OrderController->create()
#6 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
#7 C:\xampp\htdocs\Chakanoks\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Chakanoks\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\Chakanoks\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\Chakanoks\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-10-22 18:10:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'name' in 'field list'
[Method: GET, Route: orders/create]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 2 APPPATH\Controllers\OrderController.php(40): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:10:13 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 3 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 4 APPPATH\Controllers\OrderController.php(40): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-10-22 18:10:13 --> [Caused by] mysqli_sql_exception: Unknown column 'name' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`')
 4 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `supplier_id`, `name`
FROM `suppliers`
ORDER BY `name`', [], false)
 5 APPPATH\Controllers\OrderController.php(40): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\OrderController->create()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\OrderController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-10-22 18:10:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
